# Labeler configuration for hexcuit/server
# See https://github.com/actions/labeler

database:
  - changed-files:
    - any-glob-to-any-file:
      - src/db/**
      - drizzle.config.ts
      - drizzle/**

middleware:
  - changed-files:
    - any-glob-to-any-file:
      - src/middlewares/**

routes:
  - changed-files:
    - any-glob-to-any-file:
      - src/routes/**

client:
  - changed-files:
    - any-glob-to-any-file:
      - src/client.ts

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package.json
      - bun.lock

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - README.md
      - CHANGELOG.md
      - LICENSE

utils:
  - changed-files:
    - any-glob-to-any-file:
      - src/utils/**

tests:
  - changed-files:
    - any-glob-to-any-file:
      - src/**/__tests__/**
      - vitest.config.ts

core:
  - changed-files:
    - any-glob-to-any-file:
      - src/index.ts
      - src/constants/**

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - "*.config.*"
      - "*.jsonc"
      - tsconfig.json
      - biome.jsonc
      - wrangler.jsonc
      - lefthook.json
